development:
  adapter: postgresql
  database: example_rest_api_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: example_rest_api_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: example_rest_api_production
  pool: 5
  timeout: 5000